//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.08 at 08:39:47 PM CET 
//


package com.michaelhitzker.data;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for carTelemetryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="carTelemetryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cars" type="{http://www.cartelemetry.org}carsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "carTelemetryType", propOrder = {
    "cars"
})
@XmlRootElement(name = "carTelemetry")
public class CarTelemetryType {

    @XmlElement(required = true)
    protected CarsType cars;

    /**
     * Gets the value of the cars property.
     * 
     * @return
     *     possible object is
     *     {@link CarsType }
     *     
     */
    public CarsType getCars() {
        return cars;
    }

    /**
     * Sets the value of the cars property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarsType }
     *     
     */
    public void setCars(CarsType value) {
        this.cars = value;
    }

}
