//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.08 at 08:39:47 PM CET 
//


package com.michaelhitzker.data;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.michaelhitzker.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CarTelemetry_QNAME = new QName("http://www.cartelemetry.org", "carTelemetry");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.michaelhitzker.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CarTelemetryType }
     * 
     */
    public CarTelemetryType createCarTelemetryType() {
        return new CarTelemetryType();
    }

    /**
     * Create an instance of {@link CarType }
     * 
     */
    public CarType createCarType() {
        return new CarType();
    }

    /**
     * Create an instance of {@link TelemtryDataListType }
     * 
     */
    public TelemtryDataListType createTelemtryDataListType() {
        return new TelemtryDataListType();
    }

    /**
     * Create an instance of {@link TelemetryDataType }
     * 
     */
    public TelemetryDataType createTelemetryDataType() {
        return new TelemetryDataType();
    }

    /**
     * Create an instance of {@link CarsType }
     * 
     */
    public CarsType createCarsType() {
        return new CarsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CarTelemetryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cartelemetry.org", name = "carTelemetry")
    public JAXBElement<CarTelemetryType> createCarTelemetry(CarTelemetryType value) {
        return new JAXBElement<CarTelemetryType>(_CarTelemetry_QNAME, CarTelemetryType.class, null, value);
    }

}
